CREATE DATABASE paired;

CREATE TABLE IF NOT EXISTS students(
id SERIAL PRIMARY KEY,
name VARCHAR,
studentDate TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pairs(
id SERIAL PRIMARY KEY,
pairedIds VARCHAR,
pairDate TIMESTAMP
);

CREATE DATABASE paired_test WITH TEMPLATE paired;